port: 8080

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

mongo:
  uri: "mongodb://mongodb:27017"
  name: "articlesDatabase"
  user_collection: "users"
  article_collection: "article"