port: 8080

mongo:
  uri: "mongodb://127.0.0.1:27017/"
  name: "translyricsdb"
  user_collection: "users"
  article_collection: "articles"

auth:
  signing_key: "signing_key"
  token_ttl: 86400